---
# Actualización del servidor e instalación de dependencias
- name: Update Server and Install Dependencies  # Nombre descriptivo del playbook
  hosts: all  # Especifica que este playbook se ejecutará en todos los hosts definidos en el inventario
  vars:
    state: latest  # Define la variable 'state' para usar en la instalación de paquetes, asegurando la última versión
    user: developer  # Define la variable 'user' que será usada para crear un usuario en el sistema

  tasks:  # Lista de tareas a ejecutar
  - name: Add the user {{ user }}  # Descripción de la tarea
    become: yes  # Ejecuta la tarea con privilegios de superusuario
    ansible.builtin.user:  # Utiliza el módulo 'user' de Ansible para crear un usuario
      name: "{{user}}"  # Nombre del usuario a crear, utiliza la variable definida anteriormente
  
  - name: Upgrade  # Descripción de la tarea para actualizar todos los paquetes del sistema
    become: yes  # Ejecuta la tarea con privilegios de superusuario
    apt:  # Utiliza el módulo 'apt' para manejar paquetes en sistemas basados en Debian/Ubuntu
       force_apt_get: yes  # Fuerza el uso de apt-get en lugar de aptitude
       upgrade: dist  # Ejecuta una actualización de distribución, equivalente a 'dist-upgrade'
       update_cache: yes  # Actualiza el cache de apt antes de la actualización

  - name: Install dependencies  # Descripción de la tarea para instalar paquetes específicos
    become: yes  # Ejecuta la tarea con privilegios de superusuario
    ansible.builtin.apt:  # Utiliza el módulo 'apt' para instalar paquetes
      pkg:  # Lista de paquetes a instalar
      - gcc  # Compilador de C
      - python3-dev  # Herramientas de desarrollo para Python 3
      - python3-pip  # Sistema de gestión de paquetes para Python
      - python3-venv  # Herramienta para crear entornos virtuales en Python
      - libpq-dev  # Bibliotecas de desarrollo para PostgreSQL
      - build-essential  # Paquete meta para herramientas de compilación
      - libssl-dev  # Herramientas de desarrollo para SSL
      - libffi-dev  # Herramientas de desarrollo para libffi
